name: Packer Build

on: workflow_dispatch

env:
  VERSION: "latest"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Packer
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: ${{ env.VERSION }}

    - name: Change to Packer directory
      id: cd
      run: |
        cd packer
        ls
        
    - name: Initialize Packer
      id: init
      run: packer init .

    - name: Validate Packer configuration
      id: validate
      run: packer validate .

    - name: Build with Packer
      id: build
      run: packer build .
