name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print Branch Name
        id: branch_name
        run: echo "Current branch is ${{ github.ref }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        id: init
        run: terraform init

      - name: Format Terraform code
        id: fmt
        run: terraform fmt

      - name: Validate Terraform configuration
        id: validate
        run: terraform validate

      - name: Run Terraform tests (if available)
        id: test
        run: terraform test

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'master'
            ]
        extra_plugins: |
          @semantic-release/changelog@6.0.0
          @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
