name: Release

on:
  workflow_dispatch:
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic-release.outputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Branch Name
        id: branch_name
        run: echo "Current branch is ${{ github.ref }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        id: init
        run: terraform init

      - name: Format Terraform code
        id: fmt
        run: terraform fmt

      - name: Validate Terraform configuration
        id: validate
        run: terraform validate

      - name: Run Terraform tests (if available)
        id: test
        run: terraform test

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/github
            @semantic-release/exec
            @semantic-release/changelog
          branches: |
            [
              'main'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.SEC_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: Create Release
       uses: softprops/action-gh-release@v1
       with:
          tag_name: v${{ needs.build.outputs['version'] }}
          body: Release notes and changelog for v${{ needs.build.outputs['version'] }}
       env:
          GITHUB_TOKEN: ${{ secrets.SEC_TOKEN }}

