name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Print Branch Name
        id: branch_name
        run: echo "Current branch is ${{ github.ref }}"
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        id: init
        run: terraform init

      - name: Format Terraform code
        id: fmt
        run: terraform fmt

      - name: Validate Terraform configuration
        id: validate
        run: terraform validate

      - name: Run Terraform tests
        id: test
        run: terraform test  

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install semantic-release dependencies
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git

      - name: Configure semantic-release
        run: |
         echo '{"branches": ["main"], "analyzeCommits": ["feat", "fix", "breaking change"], "release": {"tagFormat": "${{ env.GITHUB_REF_SLUG }}-{version}"}, "plugins": ["@semantic-release/changelog", "@semantic-release/git"]}' > .semantic-release.json
        env:
          GITHUB_REF_SLUG: main
          
      - name: Release with semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEC_TOKEN }}
        run: npx semantic-release
