name: Release

on:
  workflow_dispatch:
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
       version: ${{ steps.semantic-release.outputs.version }}


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Branch Name
        id: branch_name
        run: echo "Current branch is ${{ github.ref }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        id: init
        run: terraform init

      - name: Format Terraform code
        id: fmt
        run: terraform fmt

      - name: Validate Terraform configuration
        id: validate
        run: terraform validate

      - name: Run Terraform tests
        id: test
        run: terraform test

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
